global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
scrape_configs:
  - job_name: 'server1-ebpf_monitor'
    static_configs:
      - targets: ['13.232.118.112:8000', '3.7.252.130:8000']
        labels:
          server_name: 'server1'
  - job_name: 'server2-ebpf_monitor'
    static_configs:
      - targets: ['13.232.118.112:8000']
        labels:
          server_name: 'server1'
      - targets: ['3.7.252.130:8000']
        labels:
          server_name: 'server2'
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
